// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: flex/vocabulary.flex

package main;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
// import javafx.util.Pair;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\3\u0100\1\u0e00\205\u0100\1\u0600\1\u0100\1\u0f00\1\u1000\1\u1100"+
    "\1\u1200\54\u0100\10\u1300\37\u0100\1\u0900\4\u0100\1\u1400\10\u0100"+
    "\1\u1500\2\u0100\1\u1600\1\u1700\1\u1200\1\u0100\1\u0500\1\u0100"+
    "\1\u1800\1\u1500\1\u0800\3\u0100\1\u1100\1\u1900\114\u0100\1\u1a00"+
    "\1\u1100\153\u0100\1\u1b00\11\u0100\1\u1c00\1\u1200\6\u0100\1\u1100"+
    "\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\13\0\3\1\2\0\1\2\2\0\1\2\15\0\1\3"+
    "\1\4\3\0\1\5\1\6\2\7\1\10\1\11\1\7"+
    "\1\11\1\12\1\13\12\14\1\0\1\7\1\15\1\16"+
    "\1\15\2\0\4\17\1\20\25\17\1\7\1\21\1\7"+
    "\1\0\1\22\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\17\1\34\1\35\1\17"+
    "\1\36\1\37\1\40\1\17\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\2\17\1\7\1\50\1\7\2\0"+
    "\5\51\1\52\u01da\51\12\53\206\51\12\53\306\51\12\53"+
    "\234\51\12\53\166\51\12\53\140\51\12\53\166\51\12\53"+
    "\106\51\12\53\u0116\51\12\53\106\51\12\53\u0146\51\12\53"+
    "\46\51\12\53\u012c\51\12\53\200\51\12\53\246\51\12\53"+
    "\6\51\12\53\266\51\12\53\126\51\12\53\206\51\12\53"+
    "\6\51\12\53\316\51\2\52\u01a6\51\12\53\46\51\12\53"+
    "\306\51\12\53\26\51\12\53\126\51\12\53\u0196\51\12\53"+
    "\6\51\u0100\52\240\51\12\53\206\51\12\53\u012c\51\12\53"+
    "\200\51\12\53\74\51\12\53\220\51\12\53\166\51\12\53"+
    "\146\51\12\53\206\51\12\53\106\51\12\53\266\51\12\53"+
    "\u0164\51\62\53\100\51\12\53\266\51";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7424];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\1\1"+
    "\1\5\1\6\1\7\1\10\12\11\1\1\1\6\1\12"+
    "\1\13\2\0\1\3\1\14\2\0\1\14\1\0\1\7"+
    "\7\11\1\15\5\11\3\0\1\16\1\0\12\11\2\0"+
    "\1\16\1\0\4\11\1\17\2\0\3\11\2\0\1\11"+
    "\2\0\1\14\1\0\1\14";

  private static int [] zzUnpackAction() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\130\0\204\0\260\0\54\0\54"+
    "\0\334\0\u0108\0\u0134\0\u0160\0\130\0\u018c\0\u01b8\0\u01e4"+
    "\0\u0210\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344"+
    "\0\u0370\0\54\0\54\0\204\0\u039c\0\54\0\u03c8\0\u03f4"+
    "\0\u0420\0\u044c\0\u0478\0\54\0\u04a4\0\u04d0\0\u04fc\0\u0528"+
    "\0\u0554\0\u0580\0\u05ac\0\u018c\0\u05d8\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0420\0\u0738\0\u0764\0\u0790"+
    "\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4\0\u08f0"+
    "\0\u091c\0\u0948\0\u03f4\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24"+
    "\0\u018c\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58"+
    "\0\u0b84\0\u0bb0\0\u0bdc\0\u091c\0\u0c08\0\54";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\2\1\7"+
    "\2\10\1\11\1\12\1\13\1\14\1\15\2\16\1\2"+
    "\2\16\1\17\1\20\1\16\1\21\1\22\2\16\1\23"+
    "\5\16\1\24\1\16\1\25\1\16\1\26\1\27\1\16"+
    "\1\30\1\2\1\3\1\31\72\0\1\32\41\0\1\33"+
    "\12\0\2\34\1\35\1\0\25\34\11\0\1\36\62\0"+
    "\1\37\47\0\1\40\2\0\1\41\52\0\1\42\1\0"+
    "\1\13\12\0\1\43\23\0\1\31\16\0\1\44\51\0"+
    "\1\16\2\0\2\16\1\0\26\16\20\0\1\16\2\0"+
    "\2\16\1\0\15\16\1\45\1\16\1\46\6\16\20\0"+
    "\1\16\2\0\2\16\1\0\15\16\1\47\10\16\20\0"+
    "\1\16\2\0\2\16\1\0\13\16\1\50\12\16\20\0"+
    "\1\16\2\0\2\16\1\0\1\16\1\51\11\16\1\52"+
    "\1\16\1\53\10\16\20\0\1\16\2\0\2\16\1\0"+
    "\6\16\1\54\5\16\1\55\11\16\20\0\1\16\2\0"+
    "\2\16\1\0\5\16\1\56\20\16\20\0\1\16\2\0"+
    "\2\16\1\0\17\16\1\57\6\16\20\0\1\16\2\0"+
    "\2\16\1\0\15\16\1\60\10\16\20\0\1\16\2\0"+
    "\2\16\1\0\10\16\1\61\15\16\54\0\1\36\17\0"+
    "\1\31\36\0\1\31\4\0\1\33\1\0\1\62\10\0"+
    "\2\34\1\35\1\0\25\34\20\0\1\37\3\0\1\63"+
    "\6\0\1\63\24\0\10\40\1\64\40\40\3\0\2\41"+
    "\1\65\46\41\17\0\1\37\12\0\1\43\73\0\1\66"+
    "\20\0\1\16\2\0\2\16\1\0\15\16\1\67\10\16"+
    "\20\0\1\16\2\0\2\16\1\0\5\16\1\70\20\16"+
    "\20\0\1\16\2\0\2\16\1\0\14\16\1\71\11\16"+
    "\20\0\1\16\2\0\2\16\1\0\20\16\1\72\5\16"+
    "\20\0\1\16\2\0\2\16\1\0\13\16\1\73\12\16"+
    "\20\0\1\16\2\0\2\16\1\0\15\16\1\74\10\16"+
    "\20\0\1\16\2\0\2\16\1\0\17\16\1\54\6\16"+
    "\20\0\1\16\2\0\2\16\1\0\21\16\1\54\4\16"+
    "\20\0\1\16\2\0\2\16\1\0\21\16\1\75\4\16"+
    "\20\0\1\16\2\0\2\16\1\0\22\16\1\76\3\16"+
    "\20\0\1\16\2\0\2\16\1\0\11\16\1\77\14\16"+
    "\20\0\1\16\2\0\2\16\1\0\11\16\1\100\14\16"+
    "\10\0\1\33\1\0\1\34\10\0\2\34\1\35\1\0"+
    "\25\34\15\0\1\101\14\0\1\102\25\0\10\40\1\64"+
    "\2\40\1\103\35\40\43\0\1\104\27\0\1\16\2\0"+
    "\2\16\1\0\13\16\1\105\12\16\20\0\1\16\2\0"+
    "\2\16\1\0\1\16\1\106\24\16\20\0\1\16\2\0"+
    "\2\16\1\0\21\16\1\107\4\16\20\0\1\16\2\0"+
    "\2\16\1\0\5\16\1\54\20\16\20\0\1\16\2\0"+
    "\2\16\1\0\20\16\1\76\5\16\20\0\1\16\2\0"+
    "\2\16\1\0\1\16\1\55\24\16\20\0\1\16\2\0"+
    "\2\16\1\0\22\16\1\110\3\16\20\0\1\16\2\0"+
    "\2\16\1\0\5\16\1\111\20\16\20\0\1\16\2\0"+
    "\2\16\1\0\4\16\1\54\21\16\20\0\1\16\2\0"+
    "\2\16\1\0\13\16\1\72\12\16\32\0\1\102\60\0"+
    "\1\112\57\0\1\113\30\0\1\16\2\0\2\16\1\0"+
    "\5\16\1\114\20\16\20\0\1\16\2\0\2\16\1\0"+
    "\12\16\1\54\13\16\20\0\1\16\2\0\2\16\1\0"+
    "\11\16\1\115\14\16\20\0\1\16\2\0\2\16\1\0"+
    "\17\16\1\116\6\16\35\0\1\117\60\0\1\120\31\0"+
    "\1\16\2\0\2\16\1\0\1\16\1\116\24\16\20\0"+
    "\1\16\2\0\2\16\1\0\14\16\1\121\11\16\20\0"+
    "\1\16\2\0\2\16\1\0\14\16\1\54\11\16\37\0"+
    "\1\122\47\0\1\123\40\0\1\16\2\0\2\16\1\0"+
    "\22\16\1\72\3\16\47\0\1\124\46\0\1\125\60\0"+
    "\1\126\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3124];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\21\1\2\11\2\0\1\11"+
    "\1\1\2\0\1\1\1\0\1\11\15\1\3\0\1\1"+
    "\1\0\12\1\2\0\1\1\1\0\5\1\2\0\3\1"+
    "\2\0\1\1\2\0\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	List<String> numbers = new ArrayList<>();
	Map<String, Token> tokens = new HashMap<>(); // List<Pair<String,Token>> Token = new ArrayList<>();
	List<String> keywords = new ArrayList<>();
    public void showRes() {
        System.out.print("Token: \n");
        for(Map.Entry<String, Token> entry : tokens.entrySet()) {
            System.out.println("Lexeme: " + entry.getKey() + ", token: " + entry.getValue());
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* Do nothing*/
            }
            // fall through
          case 16: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 17: break;
          case 3:
            { tokens.put(yytext(), Token.LOGICAL_OPERATOR);
            }
            // fall through
          case 18: break;
          case 4:
            { tokens.put(yytext(), Token.SEPARATOR);
            }
            // fall through
          case 19: break;
          case 5:
            { tokens.put(yytext(), Token.ARITHMETIC_OPERATOR);
            }
            // fall through
          case 20: break;
          case 6:
            { tokens.put(yytext(), Token.INT_LITERAL);
            }
            // fall through
          case 21: break;
          case 7:
            { tokens.put(yytext(), Token.RELATIONAL_OPERATOR);
            }
            // fall through
          case 22: break;
          case 8:
            { tokens.put(yytext(), Token.ASSIGNMENT_OPERATOR);
            }
            // fall through
          case 23: break;
          case 9:
            { tokens.put(yytext(), Token.IDENTIFIER);
            }
            // fall through
          case 24: break;
          case 10:
            { tokens.put(yytext(), Token.EQUALITY_OPERATOR);
            }
            // fall through
          case 25: break;
          case 11:
            { tokens.put(yytext(), Token.STRING_LITERAL);
            }
            // fall through
          case 26: break;
          case 12:
            { tokens.put(yytext(), Token.FLOAT_LITERAL);
            }
            // fall through
          case 27: break;
          case 13:
            { tokens.put(yytext(), Token.KEYWORD);
            }
            // fall through
          case 28: break;
          case 14:
            { tokens.put(yytext(), Token.COMMENT);
            }
            // fall through
          case 29: break;
          case 15:
            { tokens.put(yytext(), Token.BOOL_LITERAL);
            }
            // fall through
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
          scanner.showRes();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
